import { Tpl } from "../types";

export const TplCairnPl = {
  id: "477d677c-d607-431b-b98b-f6f2d11be805",
  name: "Cairn PL",
  game: "Cairn",
  file: "cs/cairn-pl.pdf",
  schemas: [
    {
      name: {
        type: "text",
        position: { x: 11.64, y: 101.07 },
        width: 48.23,
        height: 10.17,
        alignment: "center",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      notes: {
        type: "text",
        position: { x: 120.12, y: 17.2 },
        width: 80.24,
        height: 161.78,
        alignment: "left",
        fontSize: 14,
        characterSpacing: 0,
        lineHeight: 1,
      },
      str_curr: {
        type: "text",
        position: { x: 77.26, y: 23.81 },
        width: 12.51,
        height: 8.85,
        alignment: "center",
        fontSize: 24,
        characterSpacing: 0,
        lineHeight: 1,
      },
      str_base: {
        type: "text",
        position: { x: 92.29, y: 24.29 },
        width: 12.51,
        height: 8.85,
        alignment: "center",
        fontSize: 24,
        characterSpacing: 0,
        lineHeight: 1,
      },
      dex_curr: {
        type: "text",
        position: { x: 77.42, y: 58.36 },
        width: 12.51,
        height: 8.85,
        alignment: "center",
        fontSize: 24,
        characterSpacing: 0,
        lineHeight: 1,
      },
      dex_base: {
        type: "text",
        position: { x: 92.45, y: 58.57 },
        width: 12.51,
        height: 8.85,
        alignment: "center",
        fontSize: 24,
        characterSpacing: 0,
        lineHeight: 1,
      },
      wil_curr: {
        type: "text",
        position: { x: 77.31, y: 92.65 },
        width: 12.51,
        height: 8.85,
        alignment: "center",
        fontSize: 24,
        characterSpacing: 0,
        lineHeight: 1,
      },
      wil_base: {
        type: "text",
        position: { x: 92.6, y: 93.12 },
        width: 12.51,
        height: 8.85,
        alignment: "center",
        fontSize: 24,
        characterSpacing: 0,
        lineHeight: 1,
      },
      hp_curr: {
        type: "text",
        position: { x: 76.67, y: 126.67 },
        width: 12.51,
        height: 8.85,
        alignment: "center",
        fontSize: 24,
        characterSpacing: 0,
        lineHeight: 1,
      },
      hp_base: {
        type: "text",
        position: { x: 92.23, y: 126.35 },
        width: 12.51,
        height: 8.85,
        alignment: "center",
        fontSize: 24,
        characterSpacing: 0,
        lineHeight: 1,
      },
      armor: {
        type: "text",
        position: { x: 95.08, y: 151.7 },
        width: 12.51,
        height: 8.85,
        alignment: "center",
        fontSize: 24,
        characterSpacing: 0,
        lineHeight: 1,
      },
      money: {
        type: "text",
        position: { x: 22, y: 125.71 },
        width: 39.23,
        height: 8.85,
        alignment: "center",
        fontSize: 24,
        characterSpacing: 0,
        lineHeight: 1,
      },
      deprived: {
        type: "text",
        position: { x: 53.97, y: 174.4 },
        width: 9.6,
        height: 7,
        alignment: "center",
        fontSize: 19,
        characterSpacing: 0,
        lineHeight: 1,
        fontColor: "#c80404",
      },
      desc: {
        type: "text",
        position: { x: 6.88, y: 31.22 },
        width: 58.55,
        height: 64.68,
        alignment: "left",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      eq_hand1: {
        type: "text",
        position: { x: 5.29, y: 203.24 },
        width: 36.05,
        height: 36.89,
        alignment: "left",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      eq_hand2: {
        type: "text",
        position: { x: 4.97, y: 249.75 },
        width: 36.06,
        height: 36.89,
        alignment: "left",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      eq_body1: {
        type: "text",
        position: { x: 46.78, y: 204.51 },
        width: 36.06,
        height: 35.31,
        alignment: "left",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      eq_body2: {
        type: "text",
        position: { x: 46.2, y: 251.02 },
        width: 36.06,
        height: 35.57,
        alignment: "left",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      eq_1: {
        type: "text",
        position: { x: 87.21, y: 203.93 },
        width: 36.06,
        height: 36.36,
        alignment: "left",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      eq_2: {
        type: "text",
        position: { x: 87.42, y: 250.97 },
        width: 36.06,
        height: 35.57,
        alignment: "left",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      eq_3: {
        type: "text",
        position: { x: 128.64, y: 204.62 },
        width: 36.06,
        height: 35.31,
        alignment: "left",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      eq_4: {
        type: "text",
        position: { x: 128.85, y: 251.13 },
        width: 36.06,
        height: 34.25,
        alignment: "left",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      eq_5: {
        type: "text",
        position: { x: 170.13, y: 204.83 },
        width: 36.06,
        height: 35.57,
        alignment: "left",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      eq_6: {
        type: "text",
        position: { x: 170.07, y: 251.08 },
        width: 36.06,
        height: 35.83,
        alignment: "left",
        fontSize: 15,
        characterSpacing: 0,
        lineHeight: 1,
      },
      fatigue1: {
        type: "text",
        position: { x: 31.43, y: 233.35 },
        width: 9.6,
        height: 7,
        alignment: "center",
        fontSize: 19,
        characterSpacing: 0,
        lineHeight: 1,
        fontColor: "#c80404",
      },
      fatigue2: {
        type: "text",
        position: { x: 73.18, y: 232.77 },
        width: 9.6,
        height: 7,
        alignment: "center",
        fontSize: 19,
        characterSpacing: 0,
        lineHeight: 1,
        fontColor: "#c80404",
      },
      fatigue3: {
        type: "text",
        position: { x: 113.61, y: 232.98 },
        width: 9.6,
        height: 7,
        alignment: "center",
        fontSize: 19,
        characterSpacing: 0,
        lineHeight: 1,
        fontColor: "#c80404",
      },
      fatigue4: {
        type: "text",
        position: { x: 155.09, y: 232.92 },
        width: 9.6,
        height: 7,
        alignment: "center",
        fontSize: 19,
        characterSpacing: 0,
        lineHeight: 1,
        fontColor: "#c80404",
      },
      fatigue5: {
        type: "text",
        position: { x: 197.11, y: 233.13 },
        width: 9.6,
        height: 7,
        alignment: "center",
        fontSize: 19,
        characterSpacing: 0,
        lineHeight: 1,
        fontColor: "#c80404",
      },
      fatigue6: {
        type: "text",
        position: { x: 33.01, y: 280.18 },
        width: 9.6,
        height: 7,
        alignment: "center",
        fontSize: 19,
        characterSpacing: 0,
        lineHeight: 1,
        fontColor: "#c80404",
      },
      fatigue7: {
        type: "text",
        position: { x: 73.44, y: 280.15 },
        width: 9.6,
        height: 7,
        alignment: "center",
        fontSize: 19,
        characterSpacing: 0,
        lineHeight: 1,
        fontColor: "#c80404",
      },
      fatigue8: {
        type: "text",
        position: { x: 116.25, y: 279.88 },
        width: 9.6,
        height: 7,
        alignment: "center",
        fontSize: 19,
        characterSpacing: 0,
        lineHeight: 1,
        fontColor: "#c80404",
      },
      fatigue9: {
        type: "text",
        position: { x: 156.36, y: 281.02 },
        width: 9.6,
        height: 7,
        alignment: "center",
        fontSize: 19,
        characterSpacing: 0,
        lineHeight: 1,
        fontColor: "#c80404",
      },
      fatigue10: {
        type: "text",
        position: { x: 197.84, y: 280.7 },
        width: 9.6,
        height: 7,
        alignment: "center",
        fontSize: 19,
        characterSpacing: 0,
        lineHeight: 1,
        fontColor: "#c80404",
      },
    },
  ],
} as Tpl;
